ci: Add outputting to postgres test as well

diff --git a/.github/workflows/coder.yaml b/.github/workflows/coder.yaml
--- a/.github/workflows/coder.yaml
+++ b/.github/workflows/coder.yaml
@@ -415,7 +415,17 @@ jobs:
           terraform_wrapper: false
 
       - name: Test with PostgreSQL Database
-        run: make test-postgres
+        run: |
+          make test-postgres
+          ret=$?
+          if ((ret)); then
+            # Eternalize test timeout logs because "re-run failed" erases
+            # artifacts and gotestsum doesn't always capture it:
+            # https://github.com/gotestyourself/gotestsum/issues/292
+            echo "Checking gotestsum.json for panic trace:"
+            grep -A 999999 'panic: test timed out' gotestsum.json
+          fi
+          exit $ret
 
       - uses: actions/upload-artifact@v3
         if: success() || failure()
